---
  deployment:
    tasks:
      # - export DEPLOYPATH=/home/propncqq/public_html/
      # - cp -r . * $DEPLOYPATH
      - composer install
      - npm install --only=production
      - npm run prod
      - php artisan serve