---
  deployment:
    tasks:
      # set project public folder or deployment folder
      - export DEPLOYPATH=/home/propncqq/public_html/
      - export REPOPATH=/home/propncqq/repositories/

      # copy contents of the public folder alongside composer.json and composer lock into public folder
      - cp -r $REPOPATH/repo/public/* $DEPLOYPATH
      - cp -r $REPOPATH/repo/* $REPOPATH/app
      - rm -r $REPOPATH/app/public
      - yes | cp $REPOPATH/repo/composer.json $DEPLOYPATH
      - yes | cp $REPOPATH/repo/composer.lock $DEPLOYPATH
      - yes | cp $REPOPATH/data_info/.htaccess $DEPLOYPATH

      - yes | cp $REPOPATH/data_info/.env $REPOPATH/app
      - yes | cp $REPOPATH/data_info/index.php $DEPLOYPATH/app

      # install composer packages both in project repository and deployment root
      - cd $REPOPATH
      - composer install
      - cd $DEPLOYPATH
      - composer install
      # - npm install --only=production
      # - npm run prod

      # optimize and run the app

      - cd $REPOPATH
      - php artisan optimize:clear
      - php artisan serve