---
  deployment:
    tasks:
      # set project public folder or deployment folder
      - export DEPLOYPATH=/home/propncqq/public_html/
      - export REPOPATH=/home/propncqq/repositories/

      # copy contents of the public folder alongside composer.json and composer lock into public folder
      - yes | cp $REPOPATH/data_info/.env $DEPLOYPATH
      - cp -r $REPOPATH/repo/* $DEPLOYPATH
      - cp -r $REPOPATH/repo/.* $DEPLOYPATH

      - chmod -R 0777 $DEPLOYPATH/public

      # install composer packages both in project repository and deployment root
      - cd $DEPLOYPATH
      - composer install
      - php artisan optimize:clear
